import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.light },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { 
    paddingTop: Platform.OS === 'ios' ? 10 : 20,
    paddingBottom: 20,
    paddingHorizontal: 20, 
    backgroundColor: COLORS.white, 
    borderBottomWidth: 1, 
    borderBottomColor: '#eee', 
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center' 
  },
  headerTitle: { fontSize: 24, fontWeight: '800', color: COLORS.primary, textAlign: 'center' },
  headerSubtitle: { fontSize: 14, color: COLORS.dark, opacity: 0.6, textAlign: 'center' },
  tabs: { flexDirection: 'row', padding: 5, backgroundColor: COLORS.white },
  tab: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 20 },
  activeTab: { backgroundColor: COLORS.primary },
  tabText: { fontWeight: '600', color: COLORS.dark, fontSize: 12 },
  activeTabText: { color: COLORS.white },
  // Bottom Tab Bar
  bottomTabs: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5
  },
  bottomTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeBottomTab: {
    // Optionally we can add a specific style if needed, 
    // but the color change via props in App.js usually suffices.
    // Let's add a small active indicator? Or just icon color change.
  },
  bottomTabText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.dark,
    marginTop: 4,
    opacity: 0.6
  },
  activeBottomTabText: {
    color: COLORS.primary,
    opacity: 1
  },
  scroll: { padding: 15 },
  card: { backgroundColor: COLORS.white, borderRadius: 15, padding: 20, marginBottom: 20, elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8 },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: COLORS.primary, marginBottom: 15 },
  subTitle: { fontSize: 14, fontWeight: '800', color: COLORS.primary, textTransform: 'uppercase', letterSpacing: 0.5 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  label: { fontSize: 11, fontWeight: '700', color: COLORS.dark, marginBottom: 6, marginTop: 10, textTransform: 'uppercase', letterSpacing: 0.5, opacity: 0.6 },
  input: { backgroundColor: '#f9fafd', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, borderWidth: 1, borderColor: '#eaeaed', fontSize: 15, color: COLORS.dark },
  row: { flexDirection: 'row', alignItems: 'center' },
  pillScroll: { marginVertical: 10 },
  pill: { paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#f9fafd', borderRadius: 25, marginRight: 10, borderWidth: 1, borderColor: '#eaeaed', elevation: 0 },
  pillActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary, shadowColor: COLORS.primary, shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.2, shadowRadius: 4, elevation: 3 },
  pillText: { fontWeight: '700', color: COLORS.dark, fontSize: 13 },
  pillTextActive: { color: COLORS.white },
  dropdownContainer: { marginTop: 5, marginBottom: 15 },
  listItem: { padding: 15, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  listItemActive: { backgroundColor: '#f0f8ff' },
  listItemText: { fontSize: 14, color: COLORS.dark },
  settingBlock: { marginBottom: 15 },
  importBtn: { padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 15 },
  primaryBtn: { backgroundColor: COLORS.primary, padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 15 },
  secondaryBtn: { backgroundColor: '#e1e5e8', padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 15 },
  btnText: { color: COLORS.white, fontWeight: '700', fontSize: 14 },
  btnTextDark: { color: COLORS.dark, fontWeight: '700', fontSize: 14 },
  subjectItemContainer: { marginBottom: 10 },
  subjectItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.light, padding: 12, borderRadius: 10 },
  editRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.light, padding: 8, borderRadius: 10 },
  subjectName: { fontWeight: '600', color: COLORS.dark, flex: 1 },
  miniBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, justifyContent: 'center' },
  miniBtnEdit: { backgroundColor: COLORS.accent, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  miniBtnSuccess: { backgroundColor: COLORS.success, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  miniBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 12 },
  editBtn: { backgroundColor: '#e1f5fe', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  editBtnText: { color: COLORS.accent, fontWeight: 'bold', fontSize: 12 },
  deleteBtn: { backgroundColor: '#ffd4d4', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  deleteBtnText: { color: '#d00', fontWeight: 'bold', fontSize: 12 },
  errorHighlight: { color: COLORS.primary, fontWeight: 'bold', fontSize: 12, marginBottom: 10 },
  indicatorCard: { 
    padding: 16, 
    borderRadius: 14, 
    backgroundColor: COLORS.white, 
    marginBottom: 12, 
    borderWidth: 1, 
    borderColor: '#eaeaed',
    elevation: 1,
    shadowColor: '#000', shadowOffset: { width:0, height:1 }, shadowOpacity: 0.05, shadowRadius: 3
  },
  indicatorCardActive: { 
    borderColor: COLORS.primary, 
    backgroundColor: '#fffcfc',
    borderWidth: 2,
    shadowColor: COLORS.primary, shadowOffset: { width:0, height:2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2
  },
  indCode: { fontWeight: '800', color: COLORS.primary, fontSize: 15, letterSpacing: -0.3 },
  indDesc: { fontSize: 14, color: COLORS.dark, marginTop: 6, lineHeight: 20 },
  planPreview: { backgroundColor: '#ffffff', padding: 20, borderRadius: 16, borderLeftWidth: 5, borderLeftColor: COLORS.primary, elevation: 1, shadowColor: '#000', shadowOffset: {width:0, height:1}, shadowOpacity: 0.05, shadowRadius: 3, borderWidth: 1, borderColor: '#eaeaed' },
  planText: { fontSize: 14, lineHeight: 24, color: COLORS.dark },
  planTitle: { fontWeight: '800', color: COLORS.primary, marginBottom: 10, fontSize: 18, letterSpacing: -0.5 },
  planBoldLabel: { fontSize: 13, color: COLORS.dark, opacity: 0.6, fontWeight: '600' },
  toolbar: { flexDirection: 'row', flexWrap: 'wrap', backgroundColor: '#f9fafd', padding: 8, borderTopLeftRadius: 10, borderTopRightRadius: 10, borderBottomWidth: 1, borderBottomColor: '#eaeaed' },
  toolbarBtn: { paddingHorizontal: 12, paddingVertical: 8, marginRight: 6, marginBottom: 4, backgroundColor: '#fff', borderRadius: 8, minWidth: 40, alignItems: 'center', borderWidth: 1, borderColor: '#e2e8f0', shadowColor: '#000', shadowOffset: {width:0, height:1}, shadowOpacity: 0.02, shadowRadius: 1 },
  toolbarBtnText: { fontSize: 12, fontWeight: '700', color: COLORS.primary },
  divider: { height: 1, backgroundColor: '#eaeaed', marginVertical: 15 },
  previewPhase: { marginBottom: 15 },
  phaseHeader: { fontWeight: '700', fontSize: 14, color: '#1a237e' },
  activityText: { fontSize: 13, lineHeight: 18, color: COLORS.dark, marginTop: 4 },
  htmlBase: { fontSize: 13, color: COLORS.dark },
  htmlBaseSmall: { fontSize: 11, color: COLORS.dark },
  historyCard: { backgroundColor: COLORS.white, padding: 15, borderRadius: 12, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderLeftWidth: 5, borderLeftColor: COLORS.success },
  histDate: { fontWeight: '800', fontSize: 15, color: COLORS.dark },
  indicatorLabel: { fontSize: 9, fontWeight: '800', color: COLORS.primary, marginTop: 5, letterSpacing: 0.5 },
  histCode: { color: COLORS.dark, opacity: 0.8, fontSize: 13, fontWeight: '600' },
  shareLabel: { fontSize: 12, color: COLORS.accent, fontWeight: 'bold' },
  histActionBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginRight: 8 },
  histActionText: { fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: COLORS.white, borderRadius: 20, padding: 25, elevation: 10 },
  infoBox: { backgroundColor: '#f0f7ff', borderRadius: 10, padding: 15, marginVertical: 10, borderWidth: 1, borderColor: '#d1e3ff' },
  infoTitle: { fontSize: 10, fontWeight: '800', color: COLORS.accent, marginBottom: 5, letterSpacing: 1 },
  infoText: { fontSize: 13, color: COLORS.dark, marginBottom: 5, fontWeight: '600' },
  infoList: { fontSize: 12, color: COLORS.dark, opacity: 0.8, lineHeight: 18 },
  subjectRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 },
  emptyText: { textAlign: 'center', color: COLORS.dark, opacity: 0.5, marginVertical: 20 },
  helpText: { fontSize: 11, color: COLORS.dark, opacity: 0.5, marginTop: 5, textAlign: 'center' },
  selectedFileInfo: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    backgroundColor: '#fff9e6', 
    padding: 10, 
    borderRadius: 10, 
    marginTop: 15,
    borderWidth: 1,
    borderColor: '#ffeaa7'
  },
  selectedFileText: { fontSize: 13, color: COLORS.dark, fontWeight: '600', flex: 1 },
  indMeta: { fontSize: 11, color: COLORS.dark, opacity: 0.6, marginTop: 4, fontStyle: 'italic' },
  selectedDetail: { marginTop: 20, padding: 15, backgroundColor: '#f0f4ff', borderRadius: 12, borderWidth: 1, borderColor: '#d0d9ff' },
  standardBox: { backgroundColor: COLORS.white, borderRadius: 8, padding: 10, marginTop: 5, borderWidth: 1, borderColor: '#cad5ff' },
  selectedDetailText: { fontSize: 13, color: COLORS.dark, lineHeight: 18, fontWeight: '500' },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  summaryLabel: { fontSize: 11, fontWeight: '800', color: COLORS.dark, opacity: 0.5, textTransform: 'uppercase' },
  historyItemContainer: { marginBottom: 10 },
  historyItemRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    backgroundColor: COLORS.light, 
    padding: 12, 
    borderRadius: 10 
  },
  historySubjectText: { fontWeight: '600', color: COLORS.dark, flex: 1 },
  historyIndicatorText: { fontSize: 10, fontWeight: '700', color: COLORS.primary, marginTop: 4 },
  historyGroup: { marginBottom: 20 },
  historyGroupTitle: { fontSize: 12, fontWeight: '800', color: COLORS.dark, opacity: 0.4, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
  summaryValue: { fontSize: 13, fontWeight: '600', color: COLORS.dark, flex: 1, textAlign: 'right', marginLeft: 20 },
  searchContainer: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: COLORS.light, 
    borderRadius: 10, 
    paddingHorizontal: 12, 
    borderWidth: 1, 
    borderColor: '#e1e5e8' 
  },
  timeBadge: { 
    marginLeft: 15,
    backgroundColor: '#f5f5f5', 
    paddingHorizontal: 8, 
    paddingVertical: 2, 
    borderRadius: 6,
    alignSelf: 'center'
  },
  timeText: { 
    fontSize: 10, 
    fontWeight: '700', 
    color: COLORS.dark, 
    opacity: 0.5 
  },
  loaderOverlay: { 
    position: 'absolute', 
    top: 0, 
    left: 0, 
    right: 0, 
    bottom: 0, 
    backgroundColor: 'rgba(255,255,255,0.98)',
    justifyContent: 'center', 
    alignItems: 'center',
    zIndex: 9999,
    elevation: 20
  },
  paginationRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    marginTop: 20,
    paddingHorizontal: 5
  },
  pageBtn: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: COLORS.white, 
    paddingVertical: 8, 
    paddingHorizontal: 12, 
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2
  },
  pageBtnDisabled: { 
    backgroundColor: '#f9f9f9',
    borderColor: '#eee',
    elevation: 0,
    shadowOpacity: 0
  },
  pageBtnText: { 
    fontSize: 13, 
    fontWeight: '700', 
    color: COLORS.primary,
    marginHorizontal: 4
  },
  pageCircles: { 
    flexDirection: 'row', 
    alignItems: 'center' 
  },
  pageCircle: { 
    width: 6, 
    height: 6, 
    borderRadius: 3, 
    backgroundColor: '#ddd', 
    marginHorizontal: 4 
  },
  pageCircleActive: { 
    width: 20,
    backgroundColor: COLORS.primary 
  },
  // ----- MODERN UI ELEMENTS -----
  modernTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
    marginHorizontal: 15,
    marginBottom: 20,
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  modernTopRowTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.primary,
    letterSpacing: -0.5
  },
  modernItemContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)'
  },
  modernItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modernItemTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.dark,
    flex: 1,
  },
  modernItemSubtitle: {
    fontSize: 12,
    color: COLORS.dark,
    opacity: 0.6,
    marginTop: 4
  },
  pageIndicator: {
    backgroundColor: '#eef2ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.primary,
    overflow: 'hidden'
  },
  actionBtnIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5
  }
});
